![cover_images](https://camo.githubusercontent.com/3492e111812ac08200d4acd9a0dce36ff18e22be558865d26aae570f4348996c/68747470733a2f2f6a6f736570686d75636972616578636c7573697665732e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f30382f596f75547562652d446174612d4150492d4f766572766965772e6a7067)

In [104]:
# !pip install millify

In [2]:
import pandas as pd
import time
import requests
from bs4 import BeautifulSoup
import json
import random
import time
from datetime import datetime
import os
import numpy as np 
from millify import millify,prettify
from tqdm import tqdm

import cred_template

In [106]:
DEVELOPER_KEY = cred_template.API_KEY
DEVELOPER_KEY

'AIzaSyAu_qJpb657ad1CY7SO7yVAAvRH0_5JAeg'

# Youtube Channel Stats

[youtube_url](https://developers.google.com/youtube/v3/docs/channels?hl=es)

In [107]:
url = "https://www.youtube.com/channel/UCLXRGxAzeaLDGaOphqapzmg"

In [108]:
CHANNEL_ID = 'UCp0iCvHGMwyfPHpYq7n2sPw'

# Funtions

In [109]:
def get_stats(api_key, channel_id):

    url = (
        "https://youtube.googleapis.com/youtube/v3/channels"
        f"?part=snippet,statistics&id={channel_id}&key={api_key}"
    )

    response = requests.get(url).json()

    item = response["items"][0]
    stats = item["statistics"]

    date = datetime.now().strftime("%Y-%m-%d")

    data_channel = {
        "Channel_id": channel_id,
        "Created_at": date,
        "Channel_name": item["snippet"]["title"],
        "Total_Views": int(stats["viewCount"]),
        "Subscribers": int(stats["subscriberCount"]),
        "Video_count": int(stats["videoCount"])
  }
    
    return data_channel

In [110]:
print(get_stats(DEVELOPER_KEY,CHANNEL_ID))

{'Channel_id': 'UCp0iCvHGMwyfPHpYq7n2sPw', 'Created_at': '2026-07-29', 'Channel_name': 'ATARASHII GAKKO! - 新しい学校のリーダーズ', 'Total_Views': 607608221, 'Subscribers': 1750000, 'Video_count': 430}

# Channels to analize

In [111]:

with open("channels.json", "r", encoding="utf-8") as f:
        channel_ids = json.load(f)

In [113]:
def channel_stats(channel_ids, api_key):

    data = []

    tiempo = [1, 2.5, 3, 2]

    for channel_id in tqdm(channel_ids, colour="green"):

        stats = get_stats(api_key, channel_id)
        data.append(stats)

        time.sleep(random.choice(tiempo))

    return pd.DataFrame(data)

In [116]:
df_channels_final = channel_stats(channel_ids, DEVELOPER_KEY)
df_channels_final

100%|██████████| 4/4 [00:05<00:00,  1.42s/it]

,Channel_id,Created_at,Channel_name,Total_Views,Subscribers,Video_count
0,UC-2Y8dQb0S6DtpxNgAKoJKA,2026-07-29,PlayStation,6302158684,17200000,27765
1,UCo4k7uMo-JgnNaP3TbKT2Zw,2026-07-29,Ray Snakeyes,571634615,1660000,5250
2,UCRDnYaTa1XCcVzmpT1Tm2Wg,2026-07-29,戸川純,1083362,22200,62
3,UCp0iCvHGMwyfPHpYq7n2sPw,2026-07-29,ATARASHII GAKKO! - 新しい学校のリーダーズ,607608221,1750000,430

In [119]:
df_channels_short = df_channels_final[
    ["Channel_name", "Channel_id"]
].copy()

df_channels_short.to_csv("channels_to_analize.csv", index=False)
df_channels_short

                     Channel_name                Channel_id
0                     PlayStation  UC-2Y8dQb0S6DtpxNgAKoJKA
1                    Ray Snakeyes  UCo4k7uMo-JgnNaP3TbKT2Zw
2                             戸川純  UCRDnYaTa1XCcVzmpT1Tm2Wg
3  ATARASHII GAKKO! - 新しい学校のリーダーズ  UCp0iCvHGMwyfPHpYq7n2sPw

In [ ]:
df_channels_final.to_csv('channels_to_analize_final.csv', index=False)